mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ML/', include('random_forest.urls', namespace='rf')),
    path('rf/<int:rf_id>/<int:dataset_id>/<int:setlabel_id>/<int:setfitur_id>/<int:hyperparameter_id>',
         views.randomForest),
    path('rf/<int:rf_id>',
         views.randomForest2),
    path('coba/', views.coba),
    path('', views.index),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

random_forest/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import ListView, DetailView, FormView

from . import views_dataset, views_setLabel
from . import views_setFitur, views_hyperparameterRF
from . import views_randomForest

app_name = 'random_forest'

urlpatterns = [
    path('random-forest/pohon/<int:pk>/<int:no_pohon>',
         views_randomForest.get_pohon, name='random-forest-pohon'),
    path('random-forest/fitur_importance/<int:pk>',
         views_randomForest.get_fitur_importance, name='random-forest-fitur-importance'),
    path('random-forest/result/<int:pk>',
         views_randomForest.get_result, name='random-forest-result'),
    path('random-forest/detail-tree/<int:pk>',
         views_randomForest.RandomForestDetailTreeView.as_view(), name='random-forest-detail-tree'),
    path('random-forest/detail/<int:pk>',
         views_randomForest.RandomForestDetailView.as_view(), name='random-forest-detail'),
    path('random-forest/delete/<int:pk>',
         views_randomForest.RandomForestDeleteView.as_view(), name='random-forest-delete'),
    path('random-forest/create/', views_randomForest.RandomForestCreateView.as_view(),
         name='random-forest-create'),
    path('random-forest/', views_randomForest.RandomForestListView.as_view(),
         name='random-forest-index'),

    # -------------------set hyperparameter RF
    path('hyperparameter-RF/default/<int:pk>',
         views_hyperparameterRF.set_default, name='hyperparameter-RF-set-default'),
    path('hyperparameter-RF/detail/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDetailView.as_view(), name='hyperparameter-RF-detail'),
    path('hyperparameter-RF/update/<int:pk>',
         views_hyperparameterRF.HyperparameterRFUpdateView.as_view(), name='hyperparameter-RF-update'),
    path('hyperparameter-RF/delete/<int:pk>',
         views_hyperparameterRF.HyperparameterRFDeleteView.as_view(), name='hyperparameter-RF-delete'),
    path('hyperparameter-RF/create/', views_hyperparameterRF.HyperparameterRFCreateView.as_view(),
         name='hyperparameter-RF-create'),
    path('hyperparameter-RF/', views_hyperparameterRF.HyperparameterRFListView.as_view(),
         name='hyperparameter-RF-index'),

    # -------------------set fitur
    path('set-fitur/default/<int:pk>',
         views_setFitur.set_default, name='set-fitur-set-default'),
    path('set-fitur/detail/<int:pk>',
         views_setFitur.SetFiturDetailView.as_view(), name='set-fitur-detail'),
    path('set-fitur/update/<int:pk>',
         views_setFitur.SetFiturUpdateView.as_view(), name='set-fitur-update'),
    path('set-fitur/delete/<int:pk>',
         views_setFitur.SetFiturDeleteView.as_view(), name='set-fitur-delete'),
    path('set-fitur/create/', views_setFitur.SetFiturCreateView.as_view(),
         name='set-fitur-create'),
    path('set-fitur/', views_setFitur.SetFiturListView.as_view(),
         name='set-fitur-index'),

    # -------------------set label
    path('set-label/create/label-kanker/<int:id_dataset>/<str:kolom_label>',
         views_setLabel.get_label_kanker, name='set-label-get-label-kanker'),
    path('set-label/create/label/<int:id_dataset>',
         views_setLabel.get_label, name='set-label-get-label'),
    path('set-label/default/<int:pk>',
         views_setLabel.set_default, name='set-label-set-default'),
    path('set-label/detail/<int:pk>',
         views_setLabel.SetLabelDetailView.as_view(), name='set-label-detail'),
    path('set-label/update/<int:pk>',
         views_setLabel.SetLabelUpdateView.as_view(), name='set-label-update'),
    path('set-label/delete/<int:pk>',
         views_setLabel.SetLabelDeleteView.as_view(), name='set-label-delete'),
    path('set-label/create/', views_setLabel.SetLabelCreateView.as_view(),
         name='set-label-create'),
    path('set-label/', views_setLabel.SetLabelListView.as_view(),
         name='set-label-index'),

    # -------------------dataset
    path('dataset/default/<int:pk>',
         views_dataset.set_default, name='dataset-set-default'),
    path('dataset/detail/<int:pk>/boxplot/<str:list_fitur>',
         views_dataset.get_boxplot, name='dataset-detail-get-boxplot'),
    path('dataset/detail/<int:pk>/boxplot',
         views_dataset.boxplot, name='dataset-detail-boxplot'),
    path('dataset/detail-swarm-box/<int:pk>/<str:list_fitur>',
         views_dataset.get_swarm_box, name='dataset-detail-swarm-box'),
    path('dataset/detail/<int:pk>',
         views_dataset.DatasetDetailView.as_view(), name='dataset-detail'),
    path('dataset/update/<int:pk>',
         views_dataset.DatasetUpdateView.as_view(), name='dataset-update'),
    path('dataset/delete/<int:pk>',
         views_dataset.DatasetDeleteView.as_view(), name='dataset-delete'),
    path('dataset/create/', views_dataset.DatasetCreateView.as_view(),
         name='dataset-create'),
    path('dataset/', views_dataset.DatasetListView.as_view(), name='dataset-index'),


    #     path('detail/<int:id_buku>', views.detail, name='detail'),
    #     path('update/<int:id_buku>', views.update, name='update'),
    #     path('delete/<int:id_buku>', views.delete, name='delete'),
    #     path('create-file/', views.create_file, name='create-file'),
    #     path('create/', views.create, name='create'),
    #     path('', views.index, name='index'),

]

random_forest/models.py
from django.db import models
from django.utils.text import slugify


# def validate_file_extension(value):
#     import os
#     from django.core.exceptions import ValidationError
#     ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
#     valid_extensions = ['.pdf']
#     if not ext.lower() in valid_extensions:
#         raise ValidationError(u'Unsupported file extension.only PDF files')


# class Buku(models.Model):
#     title = models.CharField(max_length=255)
#     author = models.CharField(max_length=255)
#     file_data = models.FileField(
#         upload_to='buku/pdf/', validators=[validate_file_extension])
#     cover = models.ImageField(upload_to='buku/cover/', null=True, blank=True)

#     def delete(self, *args, **kwargs):
#         self.file_data.delete()
#         self.cover.delete()
#         super().delete(*args, **kwargs)

#     def __str__(self):
#         return "[{}] {}".format(self.id, self.title)

random_forest/forms.py
# membuat form
from django import forms

from .models import Buku as BukuModel


# class BukuForm(forms.ModelForm):
#     class Meta:
#         model = BukuModel
#         fields = (
#             'title',
#             'author',
#             'file_data',
#             'cover'
#         )

#         labels = {
#             'author': 'Penulis',
#             'file_data': 'File',
#             'cover': 'Sampul Buku',
#         }

#         widgets = {
#             'title': forms.TextInput(
#                 attrs={
#                     'class': 'form-control',
#                     'placeholder': 'judul buku',
#                 }
#             ),
#             'author': forms.TextInput(
#                 attrs={
#                     'class': 'form-control',
#                     'placeholder': 'nama penulis',
#                 }
#             ),
#             'file_data': forms.ClearableFileInput(
#                 attrs={
#                     'class': 'form-control',
#                 }
#             ),
#             'cover': forms.ClearableFileInput(
#                 attrs={
#                     'class': 'form-control',
#                 }
#             ),

#         }

random_forest/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views import View
from django.core.files.storage import FileSystemStorage

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import os
import matplotlib.pyplot as plt
import math
import collections
import time


def dataframe(file_dataset, separator):
    pd.set_option('colheader_justify', 'center')
    df = pd.DataFrame()
    if separator == 'koma':
        df = pd.read_csv(file_dataset, sep=',')
    elif separator == 'titik_koma':
        df = pd.read_csv(file_dataset, sep=';')
    elif separator == 'tab':
        df = pd.read_csv(file_dataset, sep='\t')
    elif separator == 'enter':
        df = pd.read_csv(file_dataset, sep='\n')

    return df


def cross_val_split(X, fold=2, seed=0):
    np.random.seed(seed)
    n_folds = fold
    size = X.shape[0]/n_folds
    X_idx = list(range(X.shape[0]))
    folds_data = []
    for i in range(n_folds):
        #         print(X_idx)
        random_idx = list(np.random.choice(X_idx, int(size), replace=False))
#         print(random_idx)
        X_idx = [idx for idx in X_idx if idx not in random_idx]
#         print(X_idx)

        folds_data.append(random_idx)
#         print("--")
    return folds_data

def confussion_matrik(actual,predict):
    TP,FP,FN,TN = 0,0,0,0
    for i,val in enumerate(actual):
        if val == 0:
            if val == predict[i]:
                TN += 1
            else:
                FP += 1
        if val == 1:
            if val == predict[i]:
                TP += 1
            else:
                FN += 1
    return TP,FP,FN,TN
 
def acc_sens_spec(actual,predict):
    TP,FP,FN,TN = confussion_matrik(actual,predict)
    accuracy,sensitivity,specifity = 0,0,0
    if (TP+FP+FN+TN) > 0 :
        accuracy = (TP+TN)/(TP+FP+FN+TN)
    if (TP+FN) > 0 :
        sensitivity = TP/(TP+FN)
    if (TN +FP) > 0 :
        specifity = TN/(TN +FP)
    
    return accuracy,sensitivity,specifity

# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
    #how many correct predictions?
    correct = 0
    #for each actual label
    for i in range(len(actual)):
        #if actual matches predicted label
        if actual[i] == predicted[i]:
            #add 1 to the correct iterator
            correct += 1
    #return percentage of predictions that were correct
    return correct / float(len(actual)) * 100.0

def kfold_cross_validation(model, X, y, n_fold=2, n_seed=0):
    folds = cross_val_split(X, fold=n_fold, seed=n_seed)
    fold_result = []
    for i in range(len(folds)):
        #     print(i)
        train = []
        for j in range(len(folds)):
            if j != i:
                train = train + folds[j]
        test = folds[i]

        X_train = X.iloc[train, :].reset_index(drop=True)
        y_train = y[train].reset_index(drop=True)

        X_test = X.iloc[test, :].reset_index(drop=True)
        y_test = y[test].reset_index(drop=True)

        t0 = time.time()
        model.fit(X_train, y_train)
        t1 = time.time()
        waktu = t1 - t0

        predict = model.predict(X_test)
        accuracy, sensitivity, specifity = acc_sens_spec(y_test, predict)

        result = [accuracy, sensitivity, specifity, waktu]
        fold_result.append(result)

    return fold_result

random_forest/templates/random_forest/hyperparameterRF/create.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    <link rel="stylesheet" href="{% static 'random_forest/css/style_form.css' %} ">
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  <a class="btn btn-secondary" href="{% url 'rf:hyperparameter-RF-index' %} ">
                    <i class='mdi mdi-keyboard-backspace'></i> All {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
        <div class='alert alert-warning'>
          <h6>Maksimal Fitur : </h6>
          <ul>
            <li>Jika diisi dengan tipe integer, misal: 5, 10, 15. Maka <u>nilai tersebut</u> yang akan di set sebagai Maksimal Fitur</li>
            <li>Jika diisi dengan tipe float, misal: 0.5, 0.6, 0.7 . Maka <u>nilai tersebut akan dikalikan dengan jumlah fitur</u> kemudian di set sebagai Maksimal Fitur</li>
            <li>Jika diisi dengan "sqrt". Maka <u>akar kuadrat dari jumlah fitur</u> yang akan di set sebagai Maksimal Fitur</li>
            <li>Jika diisi dengan "log2". Maka <u>log dari jumlah fitur</u> yang akan di set sebagai Maksimal Fitur</li>
          </ul>
          <h6> <u> Count Fitur (X) setelah cleaning</u> : {{count_x}} </h6>
          <ul>
            <li>Bila Mak fitur melebihi ukuran fitur (X) setelah proses cleaning, maka "MAKSIMAL FITUR" akan di set otomatis ke nilai maksimal fitur (X) setelah cleaning</li>
          </ul>
        </div>
       <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}

            {{form.as_p}}
         
         <br>
         <a class="btn btn-secondary" href="{% url 'rf:hyperparameter-RF-index' %} ">Cancel</a>
         <button type="submit" class="btn btn-success">submit</button>
       </form>

    </div>

{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    <script src="{% static 'random_forest/js/script.js' %}"></script>
    <script>
        (function($) {
        'use strict';
            $(function() {
              $("#hyperparameterRF").addClass('active');
              $( ".errorlist" ).addClass('alert alert-danger');


            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

random_forest/templates/random_forest/hyperparameterRF/detail.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    <link rel="stylesheet" href="{% static 'random_forest/css/style.css' %} ">
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  <a class="btn btn-secondary" href="{% url 'rf:hyperparameter-RF-index' %} ">
                    <i class='mdi mdi-keyboard-backspace'></i> All {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
    <br>
        <div class="card">
            <div class="card-header">
                <h2>{{hyperparameterRF.dataset.nama}} </h2>
                <p><u>Separator</u> : {{hyperparameterRF.dataset.separator}} </p>
                <p><u>Deskripsi</u> : {{hyperparameterRF.dataset.deskripsi}} </p>
               <a class="btn btn-primary" href="{% url 'rf:dataset-detail' hyperparameterRF.dataset.id %}" target='__blank' title='download file {{hyperparameterRF.dataset}}'>View Dataset Detail <i class="mdi mdi-file-export text-white"></i></a>
                                   
            </div>
            <div class="card-body">
                <table border='0' style='font-size : 14px'>
                    <tr>
                        <td>Data training (X)</td>
                        <td> : </td>
                        <td>Semua Fitur ({{X_shape}})</td>
                    </tr>
                    <tr>
                        <td>Kolom label (y)</td>
                        <td> : </td>
                        <td>{{hyperparameterRF.kolom_label}}</td>
                    </tr>
                    <tr>
                        <td>Nilai label kelas kanker</td>
                        <td> : </td>
                        <td>{{hyperparameterRF.nilai_label_kanker}}</td>
                    </tr>
                    <tr>
                        <td>Frekuensi kelas</td>
                        <td> : </td>
                        <td>{{count_label}}</td>
                    </tr>
                </table>
                
            </div>
        </div>
        {% comment %}  DF DESCRIBE{% endcomment %}
        <div class="card">
            <div class="card-header">
            </div>
            <div class="card-body">
                {% comment %} <img src="{% url 'rf:hyperparameter-RF-detail-boxplot' dataset.pk%}" alt="boxplot"> {% endcomment %}
                {% comment %} <iframe src="{% url 'rf:hyperparameter-RF-detail-boxplot' dataset.pk%}" frameborder="0" height="500px" width="100%"></iframe> {% endcomment %}
            </div>
        </div>

    </div>

{% endblock content %}

{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    <script src="{% static 'random_forest/js/script.js' %}"></script>
    <script>
        (function($) {
        'use strict';
            $(function() {
                //$( "#dataset" ).addClass('active');
                $("#hyperparameterRF").addClass('active');

                $('.dataframe-style').attr('border',0)
                $('.dataframe-style-2').attr('border',0)
                $('.dataframe-style').DataTable({
                  "aLengthMenu": [
                      [5, 10, 15, -1],
                      [5, 10, 15, "All"]
                  ],
                  "iDisplayLength": 5,
                  "language": {
                      search: "search : "
                  },
                  searching: true, paging: true, info: true
              });
                $('.dataframe-style-2').DataTable({
                  "aLengthMenu": [
                      [5, 10, 15, -1],
                      [5, 10, 15, "All"]
                  ],
                  "iDisplayLength": 10,
                  "language": {
                      search: "search : "
                  },
                  searching: true, paging: true, info: true
              });

            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

random_forest/templates/random_forest/hyperparameterRF/index.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %} "> {% endcomment %}
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}

    <div class=" container">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                  {% if count_fitur == 1 %}
                    <a class="btn btn-success" href="{% url 'rf:hyperparameter-RF-create' %} ">
                      <i class='mdi mdi-plus-circle-outline'></i> Tambah
                    </a>
                  {% endif %}
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
              <div class="card">
                <div class="card-header alert-warning" >
                  <h6> <u> Info Default hyperparameter RF</u> : criterion="gini"; bootstrap=True; min_samples_split=2; min_samples_leaf=1; </h6>
                  <h6> <u> Count Fitur (X) setelah cleaning</u> : {{count_x}} </h6>
                </div>
                <div class="card-body">
                  {% if count_fitur != 1 %}
                    <div class="text-center">
                      <a class="btn btn-info"  href="{% url 'rf:set-fitur-index' %}">
                        <i class="mdi mdi-lock-open-outline"></i>
                        <span class="menu-title">Silahkan Memilih Default Fitur(X) Terlebih Dahulu</span>
                      </a>
                    </div>
                  {% else %}                
                      <div class="table-responsive">
                        <table id="coba" class="table">
                          <thead>
                            <tr>
                                <th width="5%">No</th>
                                <th width="5%">Set default</th>
                                <th>Jumlah Pohon</th>
                                <th>Maksimal Fitur</th>
                                <th>Maksimal Kedalaman Pohon</th>
                                <th width="13%">Kelola</th>
                            </tr>
                          </thead>
                          <tbody>
                                
                                {% for hyperparameterRF in hyperparameterRFs %}
                                  <tr>
                                    <td>{{forloop.counter}} </td>
                                    <td>
                                      {% if hyperparameterRF.default_hyperparameter == False %}
                                        <a id="set-default-fitur" class="btn btn-info use-dataset" href="{% url 'rf:hyperparameter-RF-set-default' hyperparameterRF.id %}" title='set default {{hyperparameterRF}}'>
                                      {% else %}
                                        <a class="btn btn-secondary use-dataset" href="#" title='set default {{hyperparameterRF}}'>
                                      {% endif %}
                                      {{hyperparameterRF.default_hyperparameter}}                                  
                                          <i class="mdi mdi-lock-open-outline" style="zoom:1.5"></i>
                                        </a>
                                    </td>
                                    <td>{{hyperparameterRF.n_tree}}</td>
                                    <td>{{hyperparameterRF.max_fitur}}</td>
                                    <td>{{hyperparameterRF.max_kedalaman}}</td>
                                    <td>
                                      {% if hyperparameterRF.use_rf == 1 %}
                                        <a class="btn btn-secondary" href="#" title='detail {{hyperparameterRF}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                        <a class="btn btn-secondary" href="#" title='edit {{hyperparameterRF}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                        <a class="btn btn-secondary" href="#" title='{{hyperparameterRF}}'><i class="mdi mdi-delete-forever"></i></a>
                                      {% else %}
                                        <a class="btn btn-secondary" href="#" title='detail {{hyperparameterRF}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                        <a class="btn btn-warning" href="{% url 'rf:hyperparameter-RF-update' hyperparameterRF.id %}" title='edit {{hyperparameterRF}}'><i class="mdi mdi-eyedropper text-white"></i></a>
                                        <a id="delete-data" class="btn btn-danger" href="{% url 'rf:hyperparameter-RF-delete' hyperparameterRF.id %}" title='{{hyperparameterRF}}'><i class="mdi mdi-delete-forever"></i></a>
                                      {% endif %}
                                    </td>
                                  </tr>        
                                {% endfor %}
                          </tbody>
                        </table>
                      </div>
                  {% endif %}
                </div>
              </div>

    </div>
{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'buku/js/script.js' %}"></script> {% endcomment %}
    <script>
    (function($) {
        'use strict';
        $(function() {
            $("#hyperparameterRF").addClass('active');
            
            $('#coba').DataTable({
                "aLengthMenu": [
                    [5, 10, 15, -1],
                    [5, 10, 15, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: "search : "
                },
                searching: true, paging: true, info: true
            });

            {% if messages %}
              {% for message in messages %}
                swal({
                  type: 'success',
                  title: 'Berhasil!',
                  text: '{{message}}',
                  timer: 2500
                });
              {% endfor %}
            {% endif %}

            // action add update

              // delete
              $('body').on('click', '#delete-data', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin menghapus ' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Delete'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              setTimeout(function () { location.reload();}, 2600);
                              swal({
                                  type: 'success',
                                  title: 'Success!',
                                  text: 'Data ' + '"'+ title +'"'+ ' berhasil dihapus!',
                                  timer: 2500

                              });
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Oops...',
                                  text: 'Something went wrong!'
                              });
                          }
                      });
                  }
                  });
              });
             // set default
              $('body').on('click', '#set-default-fitur', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin melakukan ' + '"'+ title+'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Submit'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              if (response == 'success') {
                                setTimeout(function () { location.reload();}, 2600);
                                swal({
                                    type: 'success',
                                    title: 'Success!',
                                    text: '"'+ title +'"'+ ' berhasil',
                                    timer: 2500
                                });
                              }else {
                                swal({
                                  type: response,
                                  title: 'Perhatian',
                                  text: '"--pastikan mengisi form dengan nilai dan format yang diminta--"'
                              });
                              }
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Perhatian',
                                  text: '"--pastikan mengisi form dengan nilai dan format yang diminta--"'
                              });
                          }
                      });
                  }
                  });
              });

        });
    })(jQuery);
    </script>
{% endblock app_scripts %}